apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api-deployment
  labels:
    app: python-api
spec:
  replicas: 2 # <-- This runs TWO identical copies of your app for high availability
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
      - name: python-api-container
        image: debasishdocker2025/my-python-api:latest # <-- Your image!
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: python-api-service
spec:
  type: NodePort # <-- Exposes the service outside the cluster
  selector:
    app: python-api
  ports:
    - port: 8000       # The port inside the cluster
      targetPort: 8000 # The port your Python app listens on
      nodePort: 30080  # The exact port on your machine to access the app